# Automated symbolic link removal for the OSATS ASP website module
# This script should be remove all ASP specific sym-links.

echo -en "Removing the ASP website \"blog\" symbolic link... "
rm -f "~/OSATSRC/OSATS/blog" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"OSATSnewversion.php\" symbolic link... "
rm -f "~/OSATSRC/OSATS/OSATSnewversion.php" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"cpl\" symbolic link... "
rm -f "~/OSATSRC/OSATS/cpl" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"clientSpecific\" symbolic link... "
rm -f "~/OSATSRC/OSATS/clientSpecific" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"cicla\" symbolic link... "
rm -f "~/OSATSRC/OSATS/cicla" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"campaigns\" symbolic link... "
rm -f "~/OSATSRC/OSATS/campaigns" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"bugs\" symbolic link... "
rm -f "~/OSATSRC/OSATS/bugs" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"bin\" symbolic link... "
rm -f "~/OSATSRC/OSATS/bin" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"forum\" symbolic link... "
rm -f "~/OSATSRC/OSATS/forum" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"indexingTools\" symbolic link... "
rm -f "~/OSATSRC/OSATS/indexingTools" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"kb_upload\" symbolic link... "
rm -f "~/OSATSRC/OSATS/kb_upload" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"kb\" symbolic link... "
rm -f "~/OSATSRC/OSATS/kb" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"lists\" symbolic link... "
rm -f "~/OSATSRC/OSATS/lists" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"mint\" symbolic link... "
rm -f "~/OSATSRC/OSATS/mint" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"tracker\" symbolic link... "
rm -f "~/OSATSRC/OSATS/tracker" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"tarballs\" symbolic link... "
rm -f "~/OSATSRC/OSATS/tarballs" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"style.css\" symbolic link... "
rm -f "~/OSATSRC/OSATS/style.css" 2>/dev/null && echo "Success" || echo "Not Found!"
echo -en "Removing the ASP website \"professional\" symbolic link... "
rm -f "~/OSATSRC/OSATS/professional" 2>/dev/null && echo "Success" || echo "Not Found!"