<?php 

$eventCalcFields = array(
		'title'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readEventTitle',
		),
		'start'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('dateTime'),
				'handlerReadMethod'=>'readEventStart',
		),
		'startDate'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('date'),
				'handlerReadMethod'=>'readEventStartDate',
		),
		'end'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('dateTime'),
				'handlerReadMethod'=>'readEventEnd',
		),
		'endDate'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('dateTime'),
				'handlerReadMethod'=>'readEventEndDate',
		),
		'year'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readEventYear',
		),
		'month'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readEventMonth',
		),
		'day'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readEventDay',
		),
		'hour'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readEventHour',
		),
		'minute'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readEventMinute',
		),
		'date'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('date'),
				'handlerReadMethod'=>'readEventDate',
		),
		'time'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('time'),
				'handlerReadMethod'=>'readEventTime',
		),
		'startTime'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('time'),
				'handlerReadMethod'=>'readEventStartTime',
		),
		'endTime'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('time'),
				'handlerReadMethod'=>'readEventEndTime',
		),		
		'typeDesc'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readEventTypeDesc',
		),
		'userFirstName'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readUserFirstName',
		),
		'userLastName'=>array(
				'fieldTypeEnum'=>E::dataItemFieldType('string'),
				'handlerReadMethod'=>'readUserLastName',
		),
		
	);